name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Compile French
      uses: xu-cheng/latex-action@master
      with:
        root_file: CV_Chakroun.tex

    - name: Compile English
      uses: xu-cheng/latex-action@master
      with:
        root_file: CV_Chakroun_en.tex
        args: -xelatex -file-line-error -interaction=nonstopmode

    - run: mkdir -p CVs
    - run: mv CV_Chakroun.pdf CVs/CV_Chakroun_fr.pdf
    - run: mv CV_Chakroun_en.pdf CVs/
    - uses: actions/upload-artifact@master
      with:
        name: CVs
        path: CVs

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: CVs/CV_Chakroun_fr.pdf,CVs/CV_Chakroun_en.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
