name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile French
      uses: xu-cheng/latex-action@master
      with:
        root_file: CV_Chakroun.tex
    - uses: actions/upload-artifact@master
      with:
        name: CV-french
        path: CV_Chakroun.pdf
    - name: Compile English
      uses: xu-cheng/latex-action@master
      with:
        root_file: CV_Chakroun_en.tex
    - uses: actions/upload-artifact@master
      with:
        name: CV-english
        path: CV_Chakroun_en.pdf
